# Generated by Django 3.2.8 on 2022-01-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_forgetpassword_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='professional_opted_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
