# Generated by Django 3.2.8 on 2022-01-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_professional_opted_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribtion_status',
            field=models.BooleanField(default=False),
        ),
    ]
