# Generated by Django 3.2.8 on 2022-01-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_subscribtion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribtion_status',
        ),
    ]
