# Generated by Django 3.2.8 on 2022-01-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('code', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
