# Generated by Django 3.2.8 on 2022-01-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
