# Generated by Django 3.2.8 on 2022-01-18 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_service_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('monthly', 'monthly'), ('quaterly', 'quaterly'), ('hf', 'half_yearly'), ('anually', 'anually')], default='monthly', max_length=30)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=40, null=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=40, null=True)),
                ('acitve', models.BooleanField(default=False)),
                ('user_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.usermembership')),
            ],
        ),
    ]
