# Generated by Django 3.2.8 on 2022-01-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_membership_subscription_usermembership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Product',
        ),
    ]
