# Generated by Django 3.2.8 on 2022-01-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_service_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiring_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subscribed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
