# Generated by Django 3.2.8 on 2022-01-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
