# Generated by Django 3.2.8 on 2022-01-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20220126_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('monthly', 'monthly'), ('quaterly', 'quaterly'), ('hf', 'half_yearly'), ('anually', 'anually')], default='monthly', max_length=30)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
