# Generated by Django 3.2.8 on 2022-01-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_plans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='plan',
            field=models.CharField(choices=[('monthly', 'monthly'), ('quaterly', 'quaterly'), ('hf', 'half_yearly'), ('anually', 'anually')], default='monthly', max_length=30),
        ),
    ]
