# Generated by Django 3.2.8 on 2022-01-27 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0015_auto_20220126_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMembership',
            new_name='UserSubscription',
        ),
    ]
