# Generated by Django 3.2.8 on 2022-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_usersubscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproduct',
            name='expiring_on',
        ),
        migrations.RemoveField(
            model_name='serviceproduct',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='serviceproduct',
            name='subscribed_on',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='expiring_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscribed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
