# Generated by Django 3.2.8 on 2022-01-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_alter_usersubscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceproduct',
            old_name='price',
            new_name='hf_price',
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='quaterly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
