# Generated by Django 3.2.8 on 2022-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20220128_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='tansaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
