# Generated by Django 3.2.8 on 2022-02-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_usersubscription_tansaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproduct',
            name='hf_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='monthly_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='quaterly_price',
            field=models.IntegerField(null=True),
        ),
    ]
