# Generated by Django 3.2.8 on 2022-02-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_auto_20220209_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='tansaction_id',
            new_name='payment_id',
        ),
    ]
