# Generated by Django 3.2.8 on 2022-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_rename_tansaction_id_usersubscription_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='payment_id',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
