# Generated by Django 3.2.8 on 2022-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20220212_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
