# Generated by Django 3.2.8 on 2022-02-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0028_usersubscription_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
