# Generated by Django 3.2.8 on 2022-02-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_usersubscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_duration',
            field=models.CharField(choices=[('1', 'For 1 Month'), ('3', 'For 3 Month'), ('6', 'For 6 Month'), ('12', 'For 1 Year')], max_length=255, null=True),
        ),
    ]
