# Generated by Django 3.2.8 on 2022-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_auto_20220213_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_duration',
            field=models.CharField(choices=[('1', 'For 1 Month'), ('3', 'For 3 Months'), ('6', 'For 6 Months'), ('12', 'For 1 Year')], max_length=10, null=True),
        ),
    ]
