# Generated by Django 3.2.8 on 2022-01-18 21:16

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(blank=True, choices=[('The Supreme Court of India', 'The Supreme Court of India'), ('Andhra Pradesh High Court', 'Andhra Pradesh High Court'), ('Allahabad High Court', 'Allahabad High Court'), ('Bombay High Court', 'Bombay High Court'), ('Calcutta High Court', 'Calcutta High Court'), ('Chhattisgarh High Court', 'Chhattisgarh High Court'), ('Delhi High Court', 'Delhi High Court'), ('Guwahati High Court', 'Guwahati High Court'), ('Gujarat High Court', 'Gujarat High Court'), ('Himachal Pradesh High Court', 'Himachal Pradesh High Court'), ('Jammu and Kashmir High Court', 'Jammu and Kashmir High Court'), ('Jharkhand High Court\t', 'Jharkhand High Court'), ('Karnataka High Court', 'Karnataka High Court'), ('Kerala High Court', 'Kerala High Court'), ('Madhya Pradesh High Court', 'Madhya Pradesh High Court'), ('Madras High Court', 'Madras High Court'), ('Manipur High Court', 'Manipur High Court'), ('Meghalaya High Court\t', 'Meghalaya High Court'), ('Odisha High Court', 'Odisha High Court'), ('Patna High Court', 'Patna High Court'), ('Rajasthan High Court', 'Rajasthan High Court'), ('Telangana High Court', 'Telangana High Court'), ('Tripura High Court', 'Tripura High Court'), ('Uttarakhand High Court', 'Uttarakhand High Court')], max_length=255, null=True)),
                ('tribunals', models.CharField(blank=True, choices=[('Industrial Tribunal', 'Industrial Tribunal'), ('Income Tax Appellate Tribunal', 'Income Tax Appellate Tribunal'), ('Customs, Excise and Service Tax Appellate Tribunal', 'Customs, Excise and Service Tax Appellate Tribunal'), ('Appellate Tribunal under Smugglers and Foreign Exchange Manipulators Act', 'Appellate Tribunal under Smugglers and Foreign Exchange Manipulators Act'), ('Administrative Tribunal', 'Administrative Tribunal'), ('Railway Claims Tribunal', 'Railway Claims Tribunal'), ('Securities Appellate Tribunal', 'Securities Appellate Tribunal'), ('Debt Recovery Tribunal', 'Debt Recovery Tribunal'), ('The Telecom Disputes Settlement and Appellate Tribunal', 'The Telecom Disputes Settlement and Appellate Tribunal'), (' National Companies Law Appellate Tribunal', ' National Companies Law Appellate Tribunal'), ('Industrial Tribunal', 'Industrial Tribunal'), ('National Consumer Disputes Redressal Commission', 'National Consumer Disputes Redressal Commission'), ('Appellate Tribunal for Electricity', 'Appellate Tribunal for Electricity'), ('Armed Forces Tribunal', 'Armed Forces Tribunal'), ('National Green Tribunal', 'National Green Tribunal')], max_length=255, null=True)),
                ('commission', models.BooleanField(default=False)),
                ('apelLate_type', models.CharField(help_text='required', max_length=255, null=True)),
                ('judge_name', ckeditor.fields.RichTextField(help_text='all party name (required)', null=True)),
                ('case_no', ckeditor.fields.RichTextField(help_text='all case no.', null=True)),
                ('party_name', ckeditor.fields.RichTextField(help_text='all party name', null=True)),
                ('advocate_petitioner', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('advocate_respondent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('judgements', ckeditor.fields.RichTextField(help_text='required', null=True)),
                ('date', models.DateField(help_text='required', null=True)),
                ('headnote', ckeditor.fields.RichTextField(help_text='required', null=True)),
                ('references', ckeditor.fields.RichTextField(blank=True, help_text='references of previous cases', null=True)),
                ('equivalent_citations', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(help_text='case number and year (required)', null=True)),
                ('sub_title', ckeditor.fields.RichTextField(help_text='main point for decision (required)', null=True)),
                ('law_type', models.CharField(choices=[('civil', 'civil'), ('service', 'service'), ('criminal', 'criminal'), ('taxation', 'taxation'), ('corporate', 'corporate')], help_text='required', max_length=40, null=True)),
                ('sub_law_type', multiselectfield.db.fields.MultiSelectField(choices=[('service-tax', 'service-tax'), ('ipc', 'ipc'), ('crpc', 'crpc'), ('pocso', 'pocso'), ('pmla', 'pmla'), ('ni_act', 'ni_act'), ('cyber_crime', 'cyber_crime'), ('ndps', 'ndps'), ('it', 'it'), ('gst', 'gst'), ('vat', 'vat'), ('company', 'company'), ('sebi', 'sebi'), ('fema', 'fema'), ('nclt', 'nclt'), ('banking', 'banking'), ('armed force tribunal', 'armed force tribunal'), ('central civil service', 'central civil service'), ('para military', 'para military'), ('pc act', 'pc act'), ('arbitration', 'arbitration'), ('land acquisation', 'land acquisation'), ('comercial court', 'comercial court'), ('specific performance', 'specific performance'), ('others', 'others')], help_text='required', max_length=234, null=True)),
                ('law_category', models.CharField(choices=[('limitations', 'limitations'), ('negative equality', 'negative equality'), ('review', 'review'), ('reference', 'reference'), ('special relief', 'special relief'), ('execution of decree', 'executuon of decree'), ('od/ss/rd', 'Obitor Dicta / Sub Silenso-Ratio/ Decidendi'), ('binding precedent', 'bindin precedent'), ('arbitration', 'arbitration'), ('contempt', 'contempt'), ('preliminary investigation', 'preliminary investigation'), ('zimma', 'zimma'), ('bail', 'bail'), ('antibail', 'anticipatory bail'), ('sba', 'substitution by amendment'), ('s/pl', 'statutory/procedure law'), ('sas', 'search and seizure'), ('tap', 'transfer and posting'), ('fop', 'fixation of pay'), ('u/p', 'upgradation/promotion'), ('pro dpc', 'Procedure Dpc')], help_text='required', max_length=60, null=True)),
                ('reportable', models.BooleanField(default=False)),
                ('non_reportable', models.BooleanField(default=False)),
                ('over_ruled', models.BooleanField(default=False)),
                ('diary_no', models.CharField(blank=True, max_length=255, null=True)),
                ('page_no', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
