# Generated by Django 3.2.8 on 2022-01-31 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_rename_date_citation_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='uploaded_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
