# Generated by Django 3.2.8 on 2022-02-05 11:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0005_alter_citation_headnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='sub_law_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('arbitration', 'arbitration'), ('armed force tribunal', 'armed force tribunal'), ('banking', 'banking'), ('central civil service', 'central civil service'), ('comercial court', 'comercial court'), ('company', 'company'), ('crpc', 'crpc'), ('cyber_crime', 'cyber_crime'), ('fema', 'fema'), ('gst', 'gst'), ('ipc', 'ipc'), ('it', 'it'), ('land acquisation', 'land acquisation'), ('nclt', 'nclt'), ('ndps', 'ndps'), ('ni_act', 'ni_act'), ('others', 'others'), ('para military', 'para military'), ('pc act', 'pc act'), ('pmla', 'pmla'), ('pocso', 'pocso'), ('sebi', 'sebi'), ('service-tax', 'service-tax'), ('specific performance', 'specific performance'), ('vat', 'vat')], help_text='required', max_length=234, null=True),
        ),
    ]
