# Generated by Django 3.2.8 on 2022-02-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0006_alter_citation_sub_law_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='court_name',
            field=models.CharField(blank=True, choices=[('The Supreme Court of India', 'The Supreme Court of India'), ('Allahabad High Court', 'Allahabad High Court'), ('Andhra Pradesh High Court', 'Andhra Pradesh High Court'), ('Bombay High Court', 'Bombay High Court'), ('Calcutta High Court', 'Calcutta High Court'), ('Chhattisgarh High Court', 'Chhattisgarh High Court'), ('Delhi High Court', 'Delhi High Court'), ('Gujarat High Court', 'Gujarat High Court'), ('Guwahati High Court', 'Guwahati High Court'), ('Himachal Pradesh High Court', 'Himachal Pradesh High Court'), ('Jammu and Kashmir High Court', 'Jammu and Kashmir High Court'), ('Jharkhand High Court\t', 'Jharkhand High Court'), ('Karnataka High Court', 'Karnataka High Court'), ('Kerala High Court', 'Kerala High Court'), ('Madhya Pradesh High Court', 'Madhya Pradesh High Court'), ('Madras High Court', 'Madras High Court'), ('Manipur High Court', 'Manipur High Court'), ('Meghalaya High Court', 'Meghalaya High Court'), ('Odisha High Court', 'Odisha High Court'), ('Patna High Court', 'Patna High Court'), ('Rajasthan High Court', 'Rajasthan High Court'), ('Telangana High Court', 'Telangana High Court'), ('Tripura High Court', 'Tripura High Court'), ('Uttarakhand High Court', 'Uttarakhand High Court')], max_length=255, null=True),
        ),
    ]
