# Generated by Django 3.2.8 on 2022-02-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0009_auto_20220206_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
