# Generated by Django 3.2.8 on 2022-02-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0011_alter_citation_court_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='case_no',
            field=models.TextField(help_text='required', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='judge_name',
            field=models.TextField(help_text='required', null=True),
        ),
    ]
