# Generated by Django 3.2.8 on 2022-02-09 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0016_alter_citation_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='uploaded_by',
            field=models.CharField(blank=True, default=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL), editable=False, max_length=255, null=True),
        ),
    ]
