# Generated by Django 3.2.8 on 2022-02-09 18:55

from django.db import migrations, models
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0021_alter_citation_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='uploaded_by',
            field=models.CharField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, editable=False, max_length=255, null=True),
        ),
    ]
