# Generated by Django 3.2.8 on 2022-02-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0024_alter_citation_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='uploaded_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
