# Generated by Django 3.2.8 on 2022-02-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0025_alter_citation_uploaded_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='commission',
        ),
        migrations.AlterField(
            model_name='citation',
            name='court_name',
            field=models.CharField(blank=True, choices=[('Commission', 'Commission'), ('The Supreme Court of India', 'The Supreme Court of India'), ('The Allahabad High Court', 'Allahabad High Court'), ('The Andhra Pradesh High Court', 'Andhra Pradesh High Court'), ('The Bombay High Court', 'Bombay High Court'), ('The Calcutta High Court', 'Calcutta High Court'), ('The Chhattisgarh High Court', 'Chhattisgarh High Court'), ('The Delhi High Court', 'Delhi High Court'), ('The Gujarat High Court', 'Gujarat High Court'), ('The Guwahati High Court', 'Guwahati High Court'), ('The Himachal Pradesh High Court', 'Himachal Pradesh High Court'), ('The Jammu and Kashmir High Court', 'Jammu and Kashmir High Court'), ('The Jharkhand High Court\t', 'Jharkhand High Court'), ('The Karnataka High Court', 'Karnataka High Court'), ('The Kerala High Court', 'Kerala High Court'), ('The Madhya Pradesh High Court', 'Madhya Pradesh High Court'), ('The Madras High Court', 'Madras High Court'), ('The Manipur High Court', 'Manipur High Court'), ('The Meghalaya High Court', 'Meghalaya High Court'), ('The Odisha High Court', 'Odisha High Court'), ('The Patna High Court', 'Patna High Court'), ('The Rajasthan High Court', 'Rajasthan High Court'), ('The Telangana High Court', 'Telangana High Court'), ('The Tripura High Court', 'Tripura High Court'), ('The Uttarakhand High Court', 'Uttarakhand High Court')], max_length=255, null=True),
        ),
    ]
